version: '3'
services:
    node-red:
        image: nodered/node-red-docker:slim-v8
        volumes:
            - nodered:/data
        ports:
            - "1880:1880"
    mosquitto:
        image: agmangas/mosquitto-websockets
        volumes:
            - mosquitto_data:/mosquitto/data
        ports:
            - "1883:1883"
            - "9001:9001"
    gost-db:
        image: waverider93/gost-db-timescale
        volumes:
            - postgis:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/gost
        volumes:
            - gost_conf:/gostserver/config
        depends_on:
            - mosquitto
            - gost-db
        environment:
            GOST_LOG_VERBOSE_FLAG: 1
            GOST_DB_HOST: gost-db
            GOST_MQTT_HOST: mosquitto
    dashboard:
        image: geodan/gost-dashboard
        ports:
            - "8080:8080"
        depends_on:
            - gost

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped
        
volumes:
    postgis: {}
    nodered: {}
    gost_conf: {}
    mosquitto_data: {}
    pgadmin: {}
